server:
  port: 8080
spring:
  datasource:
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl